# values description
# pages; the amount of pages
# page; page+(int number | start 1)
# items; the amount of how many the page has
# slots; how many slots are the page has
# storageName; storage's displayed name
#
# item; item+(int number | start 1)
#
# slot: where a slot the item set (int number | start 0)
# materialName; item id (should write uppercase. example:DIAMOND_AXE)
# displayName; items displayed name (can use "ยง")
# lore; items lore (when want to write more than one lore, should use "," between lore.)
# amount; the items amount (int number | 1 ~ 64)
# jump; the page that jumped destination.(does not have target page, should write 0 | the default value is 0)
#
# command; this value is an optional parameter. (Click and the command that is written run. | When you want to write more than one commands, you should use "!&!" between commands.)

pages: 2

page1:

  items: 2
  slots: 9
  storageName: "Storage1"

  item1:
    slot: 0
    materialName: "STONE"
    displayName: "example 1"
    lore: "this is a stone.,this is a stone.,this is a stone"
    amount: 1

    jump: 0
    command: "/say hello world"


  item2:
    slot: 1
    materialName: "DIAMOND"
    displayName: "example 2"
    lore: ""
    amount: 1

    jump: 2
    command: "/say jumped to page 2!&!/say hello world"


page2:
  items: 1
  slots: 9
  storageName: "Storage2"

  item1:
    slot: 0
    materialName: "REDSTONE"
    displayName: "example 3"
    lore: ""
    amount: 1

    jump: 1