
pages: 2

page1:

  items: 2
  slots: 9
  storageName: "Storage1"

  item1:
    slot: 0
    materialName: "STONE"
    displayName: "example 1"
    lore: "this is a stone.,this is a stone.,this is a stone"
    amount: 1

    jump: 0


  item2:
    slot: 1
    materialName: "DIAMOND"
    displayName: "example 2"
    lore: ""
    amount: 1

    jump: 2

page2:
  items: 1
  slots: 9
  storageName: "Storage2"

  item1:
    slot: 0
    materialName: "REDSTONE"
    displayName: "example 3"
    lore: ""
    amount: 1

    jump: 1